# Generated by Django 3.2.15 on 2023-05-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='time',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
